### ISSUE TITLE
Clearinghouse Bugs and other Oddities

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/clearinghouse-code#1]
This issue was created to capture some of the bugs and other issues that arise while submitting and using the clearinghouse. For each bug, create a description of what went wrong, and attach a label.

**Comment by jwikle** [comment]
The author and other fields are set to a max of 1024 characters, which I have exceeded with one of the resources. These fields will need to increase the number of characters allowed.

**Comment by karlbenedict** [comment]
Added comment for the author field length was moved to a free-standing issue #6
