### ISSUE TITLE
Coffee and Code: R & RStudio

### ISSUE THREAD

**Issue by raisaionin** [imls-dmt/clearinghouse-code#11]
Started reviewing "Coffee and Code: R & RStudio" http://dmtclearinghouse.esipfed.org/node/10326

**Comment by raisaionin** [comment]
Completed edits and review.

**Comment by raisaionin** [comment]
Review completed.

**Comment by njhoebel** [comment]
This issue was erroneously raised in this thread rather than in the resources-workflow thread.  I will move the comments and close this issue.
